Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'macOS']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/solid' : '@same'
    'frameworks/kio' : '@same'
    'frameworks/kconfig' : '@same'
    'frameworks/kcompletion' : '@same'
    'frameworks/kservice' : '@same'
    'frameworks/threadweaver' : '@same'
    'frameworks/ki18n' : '@same'
    'frameworks/plasma-framework' : '@same'

Options:
  test-before-installing: True
